from __future__ import annotations

import json
from pathlib import Path
import typer
from rich.console import Console

console = Console()


def init(name: str = typer.Argument(..., help="Project folder name")):
    root = Path(name).resolve()
    root.mkdir(parents=True, exist_ok=True)
    (root / "docs").mkdir(exist_ok=True)

    meta = {
        "project_name": name,
        "version": "0.1",
        "artifact_prefix": "ARC",
    }
    (root / "a365kit.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    readme = f"# {name}

This folder contains governance artifacts generated by agent365-kit.
"
    (root / "README.md").write_text(readme, encoding="utf-8")

    console.print(f"✅ Initialized governance project at [bold]{root}[/bold]")
    console.print("Next: run `a365kit blueprint` inside the project folder.")
